---
auth:
  email: "<user email for sit.no>"
  password: "<user password for sit.no>"
  max_attempts: 3
booking:
  timezone: "Europe/Oslo"
  max_attempts: 10
  max_waiting_minutes: 60
cron:
  preparation_minutes: 10
  precheck_hours: 4
  sit_rezervo_dir: "/sit-rezervo"
  python_path: "<path to python>"
  log_path: "/var/log/sit-rezervo.log"
# notifications:
#   reminder_hours_before: 4
#   transfersh:
#    url: "<transfer.sh instance url>"
#   slack:
#    bot_token: "<Slack bot token>"
#    channel_id: "<Slack channel ID>"
#    user_id: "<Slack user/member ID>"
classes:
#  - activity: 331903
#    display_name: "<recognizable name for logging and notification purposes>"
#    weekday: 6
#    studio: 306
#    time:
#      hour: 12
#      minute: 00
...
