[tool.poetry]
name = "sit-rezervo"
version = "0.1.0"
description = "Automatic booking of Sit Trening group classes"
authors = ["Mathias Oterhals Myklebust <mathias@oterbust.no>"]
readme = "README.md"
packages = [{include = "sit_rezervo"}]
repository = "https://github.com/mathiazom/sit-rezervo"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/mathiazom/sit-rezervo/issues"

[tool.poetry.scripts]
sit-rezervo = "sit_rezervo.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = {extras = ["dotenv"], version = "^1.10.5"}
fastapi = "^0.88.0"
requests = "^2.28.1"
pytz = "^2022.7"
typer = "^0.7.0"
slack-sdk = "^3.19.5"
uvicorn = "^0.20.0"
python-multipart = "^0.0.5"
dataclass-wizard = {extras = ["yaml"], version = "^0.22.2"}
pyjwt = {extras = ["crypto"], version = "^2.6.0"}
sqlalchemy = "^2.0.4"
alembic = "^1.9.4"
psycopg2-binary = "^2.9.6"
rich = "^13.3.1"
orjson = "^3.8.6"
python-crontab = "^2.7.1"
deepmerge = "^1.1.0"
auth0-python = "^4.2.0"


[tool.poetry.group.dev.dependencies]
mypy = "^0.991"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
