services:
  db:
    container_name: sit-rezervo-db
    image: postgres:14.5
    restart: unless-stopped
    volumes:
      - sit-rezervo-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  db-admin:
    container_name: sit-rezervo-db-admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 18000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@example.org
      PGADMIN_DEFAULT_PASSWORD: password
  sit-rezervo:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: sit-rezervo
    # modified run server command with hot reloading
    command: ["--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      # mount source code as volume to allow hot reloading
      - "../sit_rezervo:/app/sit_rezervo"
      # app-wide configuration applied to all users
      - "./config.json:/app/config.json:ro"
      # supply env variables as file to allow access from cron
      - "./.env:/app/.env:ro"

volumes:
  sit-rezervo-data: